### ISSUE TITLE
Should we mint/burn NFLPS on every rebalance

### ISSUE THREAD

**Issue by zmanian** [VolumeFi/cellars#10]
The current rebalance function mints/burns all NFLPs on each rebalance.

Burn occurs here: https://github.com/VolumeFi/cellars/blob/main/contracts/CellarPoolShare.sol#L969-L973

Mints occur here: https://github.com/VolumeFi/cellars/blob/main/contracts/CellarPoolShare.sol#L1368-L1382

It would be nice to have a rebalance function that rebalances among existing weights without minting and burning.

**Comment by zmanian** [comment]
This isn't blocking at the moment.

Can proceed with single signer deployment without this.

**Comment by taariq** [comment]
Now I remember where I saw this! So this is still an open question.

**Comment by taariq** [comment]
We agree for right now we will do so.
