### ISSUE TITLE
Integration testing

### ISSUE THREAD

**Issue by jackzampolin** [VolumeFi/cellars#2]
Integration tests that deploy the uniswap v3 contracts and use them to create accounting tests for all of the cellar functionality. Ideally these tests are also modular so that consuming repos (such as peggyjv/sommelier) can reuse components of the test suite to test systems integrating volumefi/cellars. There is some prior art in the uni v3 staking contracts https://github.com/omarish/uniswap-v3-staker/tree/master/test that should be taken into account.

**Comment by taariq** [comment]
Tests are complete. Please check suite and re-open if we still have issues?
