### ISSUE TITLE
Accounting tests

### ISSUE THREAD

**Issue by zmanian** [VolumeFi/cellars#5]
We need tests that validate that our accounting for pool shares is correct.

Examples of such tests

1. User A adds liquidity. Owner calls rebalance. User A removes liquidity. Cellar should now now have zero assets

2. User A adds liquidity. Some trades happen on Uniswap to create fees. Owner calls reinvest. User A removes liquidity. Cellar should now have zero assets.

Looking for suggestions on additional test cases.

**Comment by taariq** [comment]
Closing for now.
